/**
 *
 * @author angellee
 */
import java.awt.Color;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.*;
import javax.swing.BoxLayout;

public class HCIProject1 extends javax.swing.JDialog {
    TranslateService service;
    Language language;
    /**
     * Creates new form JDialog
     */
    public HCIProject1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        service = new TranslateService();
        language = new Language();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userOnePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        userTwoPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        userOneLanguages = new javax.swing.JComboBox(getHash(language.Languages));
        userTwoLanguages = new javax.swing.JComboBox(getHash(language.Languages));
        userOneEnter = new javax.swing.JButton();
        userTwoEnter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        surveyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CEN 4721C Project 1");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(820, 700));

        userOnePanel.setBackground(new java.awt.Color(204, 255, 255));
        userOnePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        userOnePanel.setPreferredSize(new java.awt.Dimension(400, 450));

        javax.swing.GroupLayout userOnePanelLayout = new javax.swing.GroupLayout(userOnePanel);
        userOnePanel.setLayout(userOnePanelLayout);
        userOnePanelLayout.setHorizontalGroup(
            userOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userOnePanelLayout.createSequentialGroup()
                .addContainerGap(380, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(16, 16, 16))
        );
        userOnePanelLayout.setVerticalGroup(
            userOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(428, Short.MAX_VALUE))
        );

        userTwoPanel.setBackground(new java.awt.Color(204, 255, 255));
        userTwoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        userTwoPanel.setPreferredSize(new java.awt.Dimension(400, 450));

        javax.swing.GroupLayout userTwoPanelLayout = new javax.swing.GroupLayout(userTwoPanel);
        userTwoPanel.setLayout(userTwoPanelLayout);
        userTwoPanelLayout.setHorizontalGroup(
            userTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTwoPanelLayout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );
        userTwoPanelLayout.setVerticalGroup(
            userTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTwoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField1.setToolTipText("Type here \n");
        jTextField1.setPreferredSize(new java.awt.Dimension(85, 28));

        jTextField2.setToolTipText("Type here");
        jTextField2.setPreferredSize(new java.awt.Dimension(85, 28));
        jTextField2.setSize(new java.awt.Dimension(85, 28));

        userOneLanguages.setToolTipText("Click to choose language");

        userTwoLanguages.setToolTipText("Click to choose language");

        userOneEnter.setText("ENTER");
        userOneEnter.setToolTipText("Press ENTER to send text");
        userOneEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userOneEnterActionPerformed(evt);
            }
        });

        userTwoEnter.setText("ENTER");
        userTwoEnter.setToolTipText("Press ENTER to send text");
        userTwoEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTwoEnterActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Choose Language");

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Choose Language");

        jLabel3.setFont(new java.awt.Font("Farah", 1, 18)); // NOI18N
        jLabel3.setText("User One");

        jLabel4.setFont(new java.awt.Font("Farah", 1, 18)); // NOI18N
        jLabel4.setText("User Two");

        surveyButton.setForeground(new java.awt.Color(0, 102, 102));
        surveyButton.setText("Qualtrics Survey");
        surveyButton.setToolTipText("Click to take the survey");
        surveyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surveyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userOneLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userOneEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userOnePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userTwoLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(userTwoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userTwoEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(surveyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userOneLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(userTwoLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userOnePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addComponent(userTwoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userTwoEnter)
                    .addComponent(userOneEnter)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surveyButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userOneEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userOneEnterActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
            public void run(){
                try {
                    String sourceID = userOneLanguages.getSelectedItem().toString();
                    String source = language.Languages.get(sourceID);
                    String targetID = userTwoLanguages.getSelectedItem().toString();
                    String target = language.Languages.get(targetID);
                    String text = jTextField1.getText();
                    String translated = null;
                    
                    if(source == target){
                        translated = jTextField1.getText();
                    }
                    else
                        translated = service.translate(text, target, source);
            
                    JLabel label1 = new JLabel("<html>" + jTextField1.getText() + "</html>", JLabel.RIGHT);
                    label1.setForeground(Color.BLACK);
                    JLabel label2 = new JLabel("<html>" + translated + "</html>", JLabel.LEFT);
                    label2.setForeground(Color.BLUE);
                    userOnePanel.setLayout(new BoxLayout(userOnePanel, BoxLayout.Y_AXIS));
                    userTwoPanel.setLayout(new BoxLayout(userTwoPanel, BoxLayout.Y_AXIS));
                    userOnePanel.add(label1);
                    userTwoPanel.add(label2);
                    userOnePanel.revalidate();
                    userTwoPanel.revalidate();
                    jTextField1.setText("");
                } catch (IOException ex) {
                    Logger.getLogger(HCIProject1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_userOneEnterActionPerformed

    private void userTwoEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTwoEnterActionPerformed
SwingUtilities.invokeLater(new Runnable() {
            public void run(){
                try {
                    String sourceID = userTwoLanguages.getSelectedItem().toString();
                    String source = language.Languages.get(sourceID);
                    String targetID = userOneLanguages.getSelectedItem().toString();
                    String target = language.Languages.get(targetID);
                    String text = jTextField2.getText();
                    String translated = null;
                    
                    if(source == target){
                        translated = jTextField2.getText();
                    }
                    else
                        translated = service.translate(text, target, source);
            
                    JLabel label1 = new JLabel("<html>" + jTextField2.getText() + "</html>", JLabel.RIGHT);
                    label1.setForeground(Color.BLACK);
                    JLabel label2 = new JLabel("<html>" + translated + "</html>", JLabel.LEFT);
                    label2.setForeground(Color.BLUE);
                    userOnePanel.setLayout(new BoxLayout(userOnePanel, BoxLayout.Y_AXIS));
                    userTwoPanel.setLayout(new BoxLayout(userTwoPanel, BoxLayout.Y_AXIS));
                    userOnePanel.add(label2);
                    userTwoPanel.add(label1);
                    userOnePanel.revalidate();
                    userTwoPanel.revalidate();
                    jTextField2.setText("");

                } catch (IOException ex) {
                    Logger.getLogger(HCIProject1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_userTwoEnterActionPerformed

    private void surveyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surveyButtonActionPerformed
       try {
        //Set your page url in this string.
        String url = "https://ufl.qualtrics.com/SE/?SID=SV_0ID1Bo6h5xotyLz";
        java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
       }
       catch (java.io.IOException e) {
        System.out.println(e.getMessage());
       } 
    }//GEN-LAST:event_surveyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HCIProject1 dialog = new HCIProject1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private String[] getHash(HashMap<String, String> h) {
        String word[] = new String[h.size()];
        Set set = h.keySet();
        Iterator it = set.iterator();
        
        while(it.hasNext()){
            for(int i = 0; i < h.size(); i++){
                word[i] = it.next().toString();
            }
        }
        return word;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton surveyButton;
    private javax.swing.JButton userOneEnter;
    private javax.swing.JComboBox userOneLanguages;
    private javax.swing.JPanel userOnePanel;
    private javax.swing.JButton userTwoEnter;
    private javax.swing.JComboBox userTwoLanguages;
    private javax.swing.JPanel userTwoPanel;
    // End of variables declaration//GEN-END:variables
}